### ISSUE TITLE
Use message instead of cat()

### ISSUE THREAD

**Issue by kirillseva** [peterhurford/batchman#41]
Useful for tests, when you don't want _any_ output printed, so you can just `suppressMessages`

**Comment by peterhurford** [comment]
Or just use `verbose = FALSE` or `options('batchman.verbose' = FALSE)`.

I personally don't like the bolded aspect of messages.  And I don't think there's an actual problem here.

But I'll use `message` over `cat` for my next packages, so I don't have to use a `verbose` flag in the future.

**Comment by peterhurford** [comment]
@kirillseva Feel free to re-open if you ever have any frustrating verbose experiences.

**Comment by kirillseva** [comment]
Sure! Thanks for quick response
