### ISSUE TITLE
Add a helper to run a function unbatched

### ISSUE THREAD

**Issue by robertzk** [peterhurford/batchman#58]
```r
unbatched(some_batched_function(...))
# or:
unbatched(some_batched_function)(...)
```

**Comment by kirillseva** [comment]
second syntax is very easy because `environment(batched_fn)$before_fn == unbatched_fn`. @peterhurford @elainexmas ?

**Comment by peterhurford** [comment]
Does https://github.com/peterhurford/batchman/blob/master/R/utils.R#L21-L24 meet your needs?

**Comment by kirillseva** [comment]
@peterhurford would be nice to expose it with a more user-friendly name. make an alias?

**Comment by peterhurford** [comment]
@kirillseva What would you like to name it.  `unbatched`?

**Comment by kirillseva** [comment]
yarr
