### ISSUE TITLE
Allow partial saving of data during a large batch process

### ISSUE THREAD

**Issue by drbabar** [peterhurford/batchman#68]
New feature request:

We use batchman to pull data.  It would be useful to store said pulled data after a user specified size chunk in some temporary location so in case something goes haywire and the process terminates or crashes it would not need to re-pull the data from scratch, and we will have saved results up until the last save.  I believe modern browsers use such an approach to download and resume downloads for big files.

**Comment by peterhurford** [comment]
Have you tried using `trycatch = TRUE` and `batchman::progress()`?  It saves partial progress to your R session in memory.

**Comment by drbabar** [comment]
This sounds useful, but the progress() feature and trycatch option are not available from the top level layer used by my employer.  I'll see if I can bug them to enable these features :)
